[package]
name = "tapioca-macro"
version = "0.1.0"
authors = ["Oliver Ford <ojf13@imperial.ac.uk>"]

[lib]
proc-macro = true

[dependencies]
Inflector = "0.10.0"
quote = "0.3"
regex = "0.2"
reqwest = "0.6"
syn = "0.11"
yaml-rust = "0.3"
