[package]
name = "tapioca-derive"
version = "0.1.0"
authors = ["Oliver Ford <ojf13@imperial.ac.uk>"]

[lib]
proc-macro = true

[dependencies]
reqwest = "0.6"
syn = "0.11"
quote = "0.3"
yaml-rust = "0.3"
